packages:
  # This is an inline package to prefix the on_client_connected with the wait_until action
  # It must appear before the actual package so it becomes the orignal config and the
  # on_client_connected list from the package config is appended onto this one.
  va_connected_wait_for_ble:
    voice_assistant:
      on_client_connected:
        - wait_until:
            not: ble.enabled
        - delay: 2s
    wifi:
      on_disconnect:
        - ble.enable:
  voice-assistant: !include voice-assistant-display.yaml

esphome:
  project:
    name: "stuart-c.voice-assistant-display"
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://stuart-c.github.io/esphome-voice-assistant/voice-assistant-display.manifest.json
    update_interval: 10min

dashboard_import:
  package_import_url: github://stuart-c/voice-assistant/voice-assistant-display.yaml

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
    - script.execute: control_leds

improv_serial:

esp32_ble:
  name: va

esp32_improv:
  authorizer: center_button
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds

switch:
  - platform: template
    id: dev_firmware
    name: Dev firmware
    icon: "mdi:test-tube"
    disabled_by_default: true
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "OTA updates set to use Dev firmware"
      - lambda: id(update_http_request).set_source_url("https://stuart-c.github.io/esphome-voice-assistant/dev/voice-assistant-display.manifest.json");
      - component.update: update_http_request
    on_turn_off:
      - logger.log: "OTA updates set to use Production firmware"
      - lambda: id(update_http_request).set_source_url("https://stuart-c.github.io/esphome-voice-assistant/voice-assistant-display.manifest.json");
      - component.update: update_http_request
